### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [jobcaseinc/jobcase-gtm-tag-template#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation [url](https://github.com/jobcaseinc/jobcase-gtm-tag-template/blob/gtm-template/README.md) mentioned in the manifest file is not valid. It shows "404 Page not found error".
![image](https://user-images.githubusercontent.com/53495700/93932456-16dc6e80-fcd5-11ea-87f2-af92c0cdcb90.png)

**Comment by ajos** [comment]
Fixed the link to the documentation in metadata.yml
